jobs:
  include:
    - os: linux
      language: python
      python:
       - "3.8"
      arch: amd64
      dist: xenial
      before_install:
        - sudo apt-get update
        - sudo apt-get -y install libxml2-dev
      addons:
        apt:
          packages: 
          - cmake
          - time
      script:
        - python hello_world.py
